from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.window import Window
import os

def create_spark_session():
    """Initializes a local Spark session."""
    return SparkSession.builder \
        .appName("StockGNN_DataIngestion") \
        .config("spark.driver.memory", "4g") \
        .getOrCreate()

def process_stock_data(spark, input_path, output_path):
    """
    Simulates Spark-based ETL:
    1. Loads raw CSV/Parquet.
    2. Calculates MA5, MA10.
    3. Handles missing values.
    4. Generates label (UP/DOWN Trend).
    """
    if not os.path.exists(input_path):
        print(f"Error: Input {input_path} not found.")
        return
    
    # In a real scenario, this would read from a Data Lake (S3/HDFS/Databricks)
    # df = spark.read.csv(input_path, header=True, inferSchema=True)
    
    # For now, let's read the mock parquet generated by pandas
    df = spark.read.parquet(input_path)
    
    # 1. Feature Engineering: Moving Averages
    # Define window for each ticker sorted by date
    window_spec = Window.partitionBy("ticker").orderBy("date")
    
    # Note: Mock data only has feat1, feat2. Let's assume feat1 is the 'price'
    df = df.withColumn("ma5", F.avg("feat1").over(window_spec.rowsBetween(-4, 0)))
    df = df.withColumn("ma10", F.avg("feat1").over(window_spec.rowsBetween(-9, 0)))
    
    # 2. Handle missing values (e.g., fill with mean)
    df = df.fillna(0)
    
    # 3. Label Generation: 1 if next day price > current day price, else 0
    # (Actually we use a lead function to look ahead)
    df = df.withColumn("next_feat1", F.lead("feat1").over(window_spec))
    df = df.withColumn("label", F.when(F.col("next_feat1") > F.col("feat1"), 1).otherwise(0))
    
    # Output to Processed directory
    df.write.mode("overwrite").parquet(output_path)
    print(f"ETL Complete. Processed data saved to {output_path}")

if __name__ == "__main__":
    # Internal test for local verification
    spark = create_spark_session()
    
    # Path setup
    root_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
    input_p = os.path.join(root_dir, "data", "processed", "mock_stocks.parquet")
    output_p = os.path.join(root_dir, "data", "processed", "processed_data.parquet")
    
    process_stock_data(spark, input_p, output_p)
    spark.stop()
