#!/bin/bash -e
if [[ ! -f "/home/spark-38c91dd0-0188-48aa-8d3c-ae/tmp/uv/uv_0.6.10_linux_arm64" ]]; then
  curl -LsSf https://astral.sh/uv/0.6.10/install.sh | sh
  exec "$HOME/.local/bin/uv" "$@"
fi
exec "/home/spark-38c91dd0-0188-48aa-8d3c-ae/tmp/uv/uv_0.6.10_linux_arm64" "$@"
