tickers:
- VCB
- VHM
- VIC
- VNM
- GAS
- MSN
- HPG
- MWG
- VRE
- TCB
- BID
- CTG
- VPB
- SSI
- PLX
- FPT
- VJC
- POW
- MBB
- STB
- ACB
- HDB
- REE
- NVL
- GVR
- PDR
- TPB
- BCM
- SAB
- VIB
- DGC
- DPM
- VTP
- DCM
- HT1
- VCI
- GEX
- HSG
- DBC
- VGC
- TCH
- PVD
- NT2
- VHC
- GMD
- MSB
- DXG
- DIG
- HCM
- PHR
- KDH
- LPB
- HDG
- OCB
- SHB
- TPH
- VND
- BVH
- PNJ
- HAG
- PC1
- SCS
- HNG
- PVT
- DHC
- BWE
- KDC
- VIX
- VPI
- DXS
- IDC
- SZL
- CMG
- HDC
- PDN
- VGI
- DPG
- PAN
- GMH
- VNT
- AAA
- DCT
- PPC
- KBC
- PHC
- NLG
- DPR
- VCS
- HTN
- TRA
- VHG
- CSV
- VSH
- TCM
- DRI
- VCG
- BMI
- BTT
- SBT
- PVS
- HHS
- TCL
- HAX
- VDS
- AGG
- THG
- QNS
- VCF
- BFC
- CII
- VSC
- MIG
- FLC
- BCG
- CTD
- PVG
- NAF
- IMP
- SGN
- IDV
- VTO
- PLC
- SVC
- DAG
- IDI
- VRC
- VCX
- TTF
- TDM
- ASM
- QCG
- PET
- TNH
- KHP
- VLA
- VGS
- ANV
- SJS
- PVP
- VFC
- DRL
- PTB
- PSH
- S4A
- SFI
- FIT
- TNG
- DHA
- BMP
- SCR
- VGP
- TMT
- PMT
- VE4
- VTA
- VPG
- HQC
- HU1
- PGI
- PTT
- LCG
- ACV
- FTS
- SBV
- CDC
- VE1
- VXB
- HAH
- E1VFVN30
- PGD
- VKC
- PGT
- VNL
- TCR
- PXI
- BWS
- QBS
- CLW
- VSI
- VTZ
- HBC
- MSH
- BBC
- HCT
- VGT
- VDL
- VEA
- DHG
- GTN
- HVN
- DVP
- KOS
- PIT
- VCT
- KSB
- DVN
- HAP
- POM
- VNE
- VDB
- VNG
- VPD
- VBG
- VLB
- VLG
- VLP
- VMA
- VMC
- VMD
- VMG
- VNH
- VNI
- VNR
- VNS
- VNX
- VNY
- VNZ
- VOC
- VOS
- VPA
- VPC
- VPH
- VPL
- VPR
- VPS
- VPW
- VPX
- VQC
- VRG
- VSA
- VSE
- VSF
- VSG
- VSM
- VSN
- VST
- VTB
- VTC
- VTD
- VTE
- VTG
- VTH
- VTI
- VTJ
- VTK
- VTL
- VTM
- VTQ
- VTR
- VTS
- VTV
- VTX
- VUA
- VVN
- VVS
- VW3
- VWS
- WCS
- WSB
- WSS
- X20
- X26
- X77
- XDH
- XHC
- XLV
- XMC
- XMD
- XMP
- XPH
- YBC
- YBM
- YEG
- YTC
- AAM
- AAS
- AAT
- AAV
- ABB
- ABC
- ABR
- ABT
- ABW
- ACC
- ACE
- ACG
- ACI
- ACL
- ACM
- ACS
- ADC
- ADG
- ADP
- ADS
- AFX
- AG1
- AGF
- AGM
- AGP
- AGR
- AGX
- AIC
- AIG
- ALT
- ALV
- AMC
- AME
- AMP
- AMS
- AMV
- ANT
- APC
- APF
- APG
- APH
- APL
- APP
- APS
- APT
- ART
- ASG
- ASP
- AST
- ATA
- ATG
- ATS
- AVC
- AVF
- AVG
- BAB
- BAF
- BAL
- BAX
- BBC
- BBH
- BBM
- BBT
- BCE
- BCF
- BCR
- BCV
- BDG
- BDT
- BDW
- BED
- BEL
- BHC
- BHG
- BHH
- BHI
- BHK
- BHN
- BHP
- BHS
- BIC
- BIG
- BIO
- BKC
- BKG
- BLF
- BLI
- BLN
- BLT
- BMC
- BMD
- BMF
- BMG
- BMJ
- BMK
- BMS
- BMV
- BNA
- BNW
- BOT
- BPC
- BQB
- BQP
- BRC
- BRR
- BRS
- BSA
- BSG
- BSH
- BSI
- BSL
- BSP
- BSQ
- BSR
- BST
- BT1
- BT6
- BTD
- BTG
- BTH
- BTN
- BTP
- BTS
- BTU
- BTV
- BTW
- BVB
- BVG
- BVL
- BVN
- BVS
- BWA
- BXH

params:
  timeframe_years: 5
  ma_periods:
    - 5
    - 10
