tickers:
- GVT
- MGC
- VID
- GEG
- SWC
- SLD
- PSL
- TTZ
- CX8
- PNJ
- TMB
- NTH
- CVT
- POV
- SAM
- MTH
- SDV
- KHG
- NWT
- BAX
- FHN
- SMT
- FIT
- DBM
- NQB
- HHS
- CNG
- LBM
- NBC
- HAM
- HMD
- SC5
- HTE
- S12
- BIO
- TD6
- DAE
- ATG
- ELC
- SDN
- SFN
- NNT
- LSS
- SIV
- PRC
- VRC
- FRT
- SKH
- PMG
- SAV
- CMT
- TNP
- AMS
- BMV
- HHP
- BMF
- QNS
- CDR
- SDA
- CT3
- SSB
- PGI
- PET
- TGP
- ONE
- KLB
- HVN
- SAC
- TV3
- ITS
- HOT
- AGP
- L14
- TDP
- VIM
- QSP
- POB
- PLP
- FRM
- CMN
- PEG
- TOP
- EIN
- EME
- SJE
- BHC
- BVN
- HTG
- LAW
- SBR
- HLT
- CRC
- TDM
- DZM
- CEO
- DKG
- SCR
- HMH
- CSI
- PVO
- NTP
- HHN
- NDT
- THN
- SD3
- AGF
- DHM
- EVE
- STS
- HBC
- TLD
- CFM
- HSM
- VCS
- G20
- VTI
- NCG
- LDW
- SPB
- CDG
- SVD
- HDP
- BWE
- PCC
- TRC
- NSH
- SDG
- DP3
- LHC
- IJC
- DHN
- YTC
- YBM
- DVW
- CPH
- VSM
- DTK
- CET
- LSG
- HAD
- NSS
- TNT
- TAB
- DBT
- UEM
- PPC
- PSG
- MA1
- VTM
- DP1
- HEV
- AVF
- CGV
- HU6
- SJD
- PEQ
- ABR
- SSC
- CLH
- TAR
- NVB
- CLW
- HES
- TDG
- VBH
- PCT
- BWS
- SII
- HKB
- ACB
- DRG
- TMS
- BMG
- LM3
- VIN
- BLT
- HPT
- TQW
- PSI
- NDX
- ICF
- VIW
- NDC
- PIS
- SPV
- KOS
- M10
- MSH
- CHP
- TDS
- CAD
- SGC
- PMS
- BPC
- TVN
- ART
- SHC
- HPA
- ADP
- SDP
- HSV
- TCX
- CTX
- TTT
- DAH
- DFF
- VHH
- VMG
- PTC
- HPD
- C69
- HLC
- PGB
- BHH
- ACL
- SDU
- TRA
- D11
- VSA
- LCD
- TBD
- PEN
- MSB
- ILA
- NBT
- UDL
- NUE
- VPG
- TJC
- SCL
- DHB
- BKG
- PTE
- NST
- MAS
- CIG
- L43
- SPI
- KST
- SBG
- PTL
- SGP
- TDT
- DGW
- CMG
- FT1
- TSC
- MPC
- TSG
- NHV
- HAF
- WSB
- LAI
- CST
- CTP
- MH3
- SIP
- VC9
- PIC
- APF
- DLT
- DOP
- CT6
- FIC
- MBS
- NDW
- SHG
- SHA
- HAT
- HUG
- PSH
- VBG
- PNT
- HPX
- QTC
- BLN
- SSI
- LIG
- NGC
- HRC
- PFL
- EID
- BIC
- ECI
- LQN
- ILS
- VCM
- BQB
- BSL
- MRF
- MGG
- CAP
- IPA
- MDF
- SPM
- DDN
- BGW
- MKV
- TMW
- BMJ
- VNC
- SSN
- PIT
- SMC
- SEB
- MHC
- LCM
- CKG
- PCE
- TB8
- QNU
- BOT
- KHX
- VKC
- VVN
- TYA
- DSN
- TSJ
- BMC
- ICT
- TAL
- VIE
- STB
- HTN
- PTS
- HNR
- BWA
- DDB
- DCV
- TVM
- PVS
- PRO
- DID
- TS3
- S74
- HEJ
- ACE
- DMC
- BNW
- CQT
- CTT
- SDC
- S55
- PPH
- TMT
- CNN
- KBC
- PMC
- CAR
- PPP
- PDV
- CTF
- PRE
- DRH
- VCG
- SZB
- SKN
- RCL
- QNP
- HTI
- GH3
- LIX
- DPP
- BTW
- VPW
- VLG
- AMV
- RBC
- SVN
- TTB
- ACV
- SDK
- TVB
- TDW
- HAV
- DHG
- HVT
- HBD
- MVN
- BID
- ACS
- ATA
- PWS
- BSQ
- SNZ
- SAL
- HFB
- GDA
- DCM
- AVG
- VHG
- DRI
- IDI
- VHC
- CSV
- EVF
- MBG
- RAT
- THS
- NAB
- SAB
- BRR
- TH1
- TXM
- TN1
- TED
- CQN
- MTB
- ECO
- SHE
- BTP
- AAT
- PBP
- NSL
- CMP
- IBD
- SGT
- KVC
- VMS
- SMN
- HSA
- IDP
- CHC
- ICG
- FGL
- HNP
- NAC
- MCH
- PMT
- SHN
- BCF
- TNH
- BCB
- HMR
- BCE
- CMF
- MTV
- VCA
- ABT
- SSH
- CTD
- HLY
- NBP
- PVV
- MVB
- PVD
- HAC
- ASP
- TW3
- QCC
- SID
- TCH
- X77
- DHA
- DS3
- THD
- PC1
- AG1
- L10
- VTJ
- HAS
- PTB
- TT6
- SJG
- AGM
- VSG
- VEC
- DNE
- VCK
- DGT
- DVP
- VCP
- OCH
- JVC
- STP
- NKG
- SD8
- LBE
- VCC
- NDP
- CIP
- EBS
- UMC
- PVX
- SBH
- BVG
- PHN
- DNC
- PNP
- HSP
- QTP
- SPH
- HWS
- AAA
- TL4
- NSG
- GSM
- MCF
- KHS
- HAR
- PTT
- CCV
- TNB
- PCM
- LM7
- L40
- DVT
- TNS
- BMP
- TCI
- VNP
- TNG
- FCC
- BSR
- CLC
- VPL
- HIO
- TNV
- PXS
- PVT
- ASG
- MEC
- MCG
- CLM
- TCK
- CHS
- KHP
- HDW
- BTU
- DIG
- TBC
- C22
- DPC
- APS
- HPW
- VCE
- HD8
- VE1
- BBM
- VFC
- DXL
- SGR
- BSG
- DC1
- VBB
- MPT
- VTZ
- CI5
- PPS
- VTH
- DRC
- FID
- PMW
- TNM
- GDW
- MEF
- PVY
- SJS
- VCR
- MIC
- VCF
- TST
- AGX
- TID
- DTP
- ASM
- VTD
- VIC
- VES
- SBV
- HUB
- VCI
- FRC
- MTA
- SRA
- OGC
- DNN
- C47
- DTE
- DVC
- FBC
- SSM
- NTC
- SB1
- CCP
- DWC
- AME
- KSB
- VSI
- BHG
- PTD
- DTH
- TKU
- DAD
- XHC
- VE2
- VJC
- VPI
- FOX
- LGC
- NAG
- SGH
- HT1
- HCI
- TLP
- TRV
- CDO
- C32
- CKV
- NTW
- FTS
- VDP
- PBT
- VSN
- VPX
- TLG
- CTW
- IDJ
- SGS
- VHF
- G36
- HRB
- TEG
- DXV
- VNA
- HUT
- ALT
- KCB
- TCM
- BSI
- DNM
- DDG
- SD4
- CNC
- PGC
- NAS
- V21
- CH5
- PND
- MAC
- HJC
- TCJ
- PVG
- TA6
- THP
- ITC
- HPM
- TCB
- BTV
- LUT
- ICC
- BTS
- DND
- VND
- ABC
- SHS
- VTG
- SJM
- VEF
- HFX
- DDM
- STC
- D2D
- BQP
- AAM
- VXP
- HU4
- PTH
- DC2
- IDV
- VFR
- VC7
- DVG
- S99
- APP
- NAP
- HNF
- ITD
- PMJ
- INC
- MED
- CTI
- NHT
- VWS
- MES
- VGR
- BIG
- PDC
- PIA
- TPB
- PHS
- VNR
- LPB
- SGB
- TCD
- VTE
- THT
- SCD
- POT
- SKV
- SHI
- ODE
- MTL
- VFG
- PJT
- TCW
- VGG
- OIL
- PXL
- PDB
- DLD
- F88
- DAN
- VRE
- BTH
- TNA
- BCA
- HFC
- PAS
- VNG
- DCF
- AVC
- WSS
- TV2
- MNB
- TMC
- VPS
- SDT
- NFC
- SRB
- VLA
- MWG
- BCP
- PCF
- KSV
- PIV
- INN
- NNC
- NHH
- TQN
- GGG
- TMP
- CSM
- DAT
- GPC
- TIX
- UPS
- VPB
- STG
- DMS
- L35
- DNT
- MLC
- SBA
- ANV
- LAS
- PMB
- ADG
- EGL
- MTG
- VSH
- BMD
- NAF
- SMA
- FDC
- TRS
- TSA
- VNZ
- ADS
- PAP
- SCS
- AIG
- BBH
- CC1
- S4A
- HC1
- SIG
- VCB
- DHD
- VEA
- QCG
- SDD
- XDH
- IRC
- VTV
- ACM
- RCC
- PGS
- ICN
- PLO
- VHM
- CTR
- VCX
- TDC
- TBW
- FCS
- SBB
- HCD
- BHI
- KMR
- VAV
- TUG
- DXS
- TTD
- AST
- HU1
- KIP
- TKC
- ACC
- UTT
- HVH
- NVP
- HCT
- PVH
- HHC
- GEE
- EMG
- APL
- CRE
- BSD
- HNA
- XLV
- V12
- VIX
- KPF
- DWS
- CKD
- MZG
- SHP
- EMS
- SZG
- VST
- VNM
- LMI
- DHT
- ABB
- SBT
- ILC
- AAV
- HLD
- HTM
- HTV
- SJ1
- C4G
- AMP
- HMC
- BXH
- RTB
- SZL
- GAS
- SRF
- PXI
- NCS
- EVS
- RGG
- UPH
- HTT
- NBE
- HEP
- TCR
- RCD
- THU
- BHP
- KTS
- DVN
- VFS
- VET
- WCS
- BTT
- CPC
- HCC
- YEG
- SBM
- VMK
- VHD
- HKT
- VAB
- MFS
- MBB
- CMI
- TOS
- VTP
- IN4
- DSD
- VTX
- VDL
- HBH
- SVG
- CK8
- SZC
- BBS
- HBS
- VTB
- SLS
- HHV
- LNC
- NHA
- DL1
- CMM
- TNI
- DPR
- GCF
- GVR
- GTD
- KDM
- TVC
- VTS
- DCG
- BTD
- TDB
- HD2
- HDA
- VGI
- YBC
- HTC
- UPC
- DAG
- APH
- L18
- PJC
- SEA
- TCO
- VNX
- PPT
- DSH
- DP2
- HAH
- LCG
- PBC
- HHG
- LIC
- PGT
- PRT
- CTB
- SCG
- C21
- KTC
- VPH
- PSW
- NVT
- VTO
- CMV
- VC1
- AAH
- BNA
- KHW
- PVP
- TDF
- VNT
- VPA
- CDN
- UCT
- HQC
- VLB
- VNY
- BCM
- VAF
- THB
- NSC
- DXG
- TTL
- REE
- VTR
- VIF
- SCC
- DBC
- CMS
- IHK
- CMW
- NXT
- AGR
- DTL
- HVX
- VIG
- IME
- DCT
- DLG
- AAS
- DTC
- ONW
- SKG
- PSB
- CVN
- NDN
- VC6
- TVH
- PPY
- VDT
- ORS
- SD5
- TCT
- PVC
- SVT
- STH
- GHC
- HAN
- SDY
- NCT
- VIT
- L63
- TOW
- SD7
- CMC
- MTS
- VQC
- FIR
- GIC
- BMK
- VUA
- PSE
- LTC
- PTG
- VIB
- NLG
- KKC
- VLC
- ATS
- GTT
- VE4
- SEP
- TAN
- CAT
- APG
- FTM
- SCO
- BEL
- HPP
- SHB
- CBS
- VE9
- NTT
- CMX
- RAL
- LCC
- SFG
- TVS
- ISG
- VGV
- TTN
- CEN
- TVT
- CDC
- HPH
- TMG
- LMH
- BMS
- SFC
- TSB
- NET
- DDV
- HOM
- ND2
- TOT
- MST
- PCG
- HDB
- BTB
- LG9
- BSH
- QNW
- PQN
- CCA
- DBD
- DOC
- TVD
- QNT
- CCS
- ADC
- APC
- VGC
- RYG
- CBI
- PVL
- DC4
- COM
- CCL
- STW
- ALC
- BTG
- VC3
- L12
- GTS
- FCN
- KHD
- HTL
- GDT
- SJF
- ABI
- THM
- TVG
- TGG
- IMP
- CJC
- MSN
- PV2
- CII
- STD
- OCB
- MDC
- TCL
- DTT
- CTG
- UIC
- NQN
- UDC
- DPM
- VE8
- LKW
- NTL
- TTH
- DTD
- BRC
- AFX
- KGM
- FOC
- DM7
- CMD
- USC
- MML
- POM
- DCL
- DMN
- BTN
- S72
- ACG
- MDG
- CCT
- DHP
- HPO
- MGR
- QHD
- POW
- CIA
- CLL
- BT6
- HTP
- PAI
- LGL
- APT
- QPH
- VXT
- TV4
- TRT
- VMA
- TTG
- CLX
- PVR
- PHP
- GIL
- BFC
- GLW
- PTV
- TIG
- VGP
- MTP
- GLC
- TR1
- BCR
- PHH
- VXB
- PHR
- HVA
- PPI
- FPT
- SD2
- KSQ
- PCH
- BKC
- DCH
- CDP
- DGC
- HLO
- NLS
- VMC
- NVL
- VTK
- LAF
- MHL
- LHG
- TPC
- AIC
- VSC
- SGI
- PTX
- DVM
- DAS
- MCP
- PVI
- PNG
- VNS
- VPC
- IDC
- THG
- VTQ
- BMI
- TKA
- PX1
- E29
- PVM
- MBT
- SFI
- L62
- RDP
- QST
- HDM
- FCM
- KDC
- VGS
- BCC
- MQN
- CPI
- QHW
- LO5
- CAN
- POS
- PAT
- BT1
- UXC
- ABS
- VCT
- DPG
- MND
- BDT
- NDF
- SD6
- DKC
- SGN
- LDP
- NJC
- TTC
- PID
- HEC
- SPC
- PXA
- VPR
- H11
- VDN
- SCJ
- PLE
- GMH
- FTI
- PGV
- XMP
- DSG
- BBT
- SRC
- KSD
- NT2
- NRC
- SGD
- DSC
- DCS
- PTI
- TNC
- VRG
- HC3
- STL
- LEC
- PPE
- QNC
- PAC
- DIH
- PLA
- MDA
- GMX
- VNF
- SBS
- GTA
- CRV
- DAC
- IVS
- PSD
- PTM
- HGM
- ANT
- VBC
- CCM
- LPT
- BHK
- DHC
- VOS
- TLH
- CCR
- MSR
- CCC
- ALV
- BAB
- ARM
- BRS
- DRL
- L61
- HMS
- HD6
- ITA
- STK
- BVB
- PSC
- HGT
- PJS
- CNT
- DTG
- PSP
- CKA
- GKM
- TV6
- RIC
- PNC
- GMC
- TDH
- HU3
- X20
- IST
- VSE
- BDG
- DDH
- TMX
- HLA
- DPH
- GCB
- EIB
- NHC
- TFC
- NO1
- HNI
- GND
- TIS
- MIE
- HNB
- GMA
- HND
- TIP
- GEX
- AMC
- MIG
- GEL
- FMC
- KTL
- VNB
- NAW
- UDJ
- PTP
- QBS
- HAX
- TTF
- ITQ
- MLS
- CSC
- MCM
- BDW
- PDR
- HNG
- SBD
- VMT
- TTA
- VHE
- HLS
- VW3
- PVE
- ST8
- API
- VLW
- ISH
- VHL
- KDH
- PAN
- DST
- HPI
- DCR
- HPB
- SVH
- ABW
- SCI
- CTA
- NOS
- PXT
- GER
- SP2
- MBN
- VTC
- SVC
- XMD
- MQB
- IFS
- TBR
- DNH
- EVG
- NBW
- HSL
- NBB
- DXP
- HNM
- KSF
- BCV
- TTS
- VMD
- SMB
- VDB
- AGG
- DNW
- VPD
- MPY
- BLI
- LMC
- DTA
- BVH
- EIC
- TIE
- DFC
- VVS
- SAF
- DNP
- HAG
- CPA
- VDG
- NED
- MKP
- VNL
- VLP
- VIP
- HDG
- X26
- PGD
- SSG
- USD
- PDN
- CID
- TA9
- BGE
- PMP
- A32
- TIN
- VIR
- PSN
- DLR
- LTG
- SSF
- HCM
- TPS
- VE3
- TAW
- HMG
- PTO
- VLS
- CNA
- FSO
- PGN
- GSP
- VTA
- THW
- LM8
- SNC
- E12
- VSF
- ICI
- OPC
- TPP
- FHS
- HID
- EFI
- TTE
- SD9
- BLF
- KTT
- BCG
- KMT
- CYC
- GLT
- C92
- PXM
- VNH
- BAL
- UNI
- NAU
- TET
- DUS
- L45
- PLX
- SAS
- MCC
- BVL
- BVS
- BHA
- XMC
- VC2
- HPG
- DTI
- HJS
- VKP
- GMD
- NAV
- VDS
- HLB
- HAP
- CMK
- CCI
- SED
- VNI
- TNW
- BSP
- VNE
- SPD
- HHB
- WTC
- VGL
- STT
- DQC
- DNA
- CAG
- DSP
- NTF
- PHC
- HII
- CFV
- SZE
- DNL
- LDG
- MVC
- PVB
- BED
- LLM
- XPH
- TSD
- CTS
- VGT
- BHN
- BSA
- PLC
- SBL
- ILB
- TV1
- HDC
- JOS
- DSE
- BAF
- TVA
- PWA
- HSG
- MEL
- DIC
- MCO

params:
  timeframe_years: 5
  ma_periods:
    - 5
    - 10
