import pandas as pd
import numpy as np

def compute_rsi(data, periods=14):
    delta = data.diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=periods).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=periods).mean()
    rs = gain / loss
    return 100 - (100 / (1 + rs))

def compute_macd(data, short_window=12, long_window=26, signal_window=9):
    short_ema = data.ewm(span=short_window, adjust=False).mean()
    long_ema = data.ewm(span=long_window, adjust=False).mean()
    macd = short_ema - long_ema
    signal = macd.ewm(span=signal_window, adjust=False).mean()
    return macd, signal

def engineer_features(input_path="data/processed/clean_data.parquet", output_path="data/processed/feature_table.parquet"):
    print(f"Engineering features from {input_path}...")
    df = pd.read_parquet(input_path)
    
    # Sort by date just in case
    if 'date' in df.columns:
        df = df.sort_values('date')
    
    # Moving Averages
    df['ma5'] = df['close'].rolling(window=5).mean()
    df['ma10'] = df['close'].rolling(window=10).mean()
    df['ma20'] = df['close'].rolling(window=20).mean()
    
    # RSI & MACD
    df['rsi'] = compute_rsi(df['close'])
    df['macd'], df['macd_signal'] = compute_macd(df['close'])
    
    # Return (log return)
    df['log_return'] = np.log(df['close'] / df['close'].shift(1))
    
    # Volatility
    df['volatility_20'] = df['log_return'].rolling(window=20).std()
    
    # Label: T+1 (Up = 1, Down = 0)
    df['target_close'] = df['close'].shift(-1)
    df['label'] = (df['target_close'] > df['close']).astype(int)
    
    # Drop NaNs generated by rolling/shifting
    df.dropna(inplace=True)
    
    df.to_parquet(output_path, index=False)
    print(f"Saved feature table to {output_path}")
    return df

if __name__ == "__main__":
    engineer_features()
